### ISSUE TITLE
IndexError while annotate certain skill

### ISSUE THREAD

**Issue by GordonYeh39** [AnasAito/SkillNER#44]
**Describe the bug**
while using skill_extractor.annotate(text) to annotate certain skill it returns error

**To Reproduce**
Here are some examples to reproduce the behavior:

1. 
text= "IDS/IPS sensors are collecting"
skill_extractor.annotate(text)

the main error is resulted from the skill "IDS"

**Comment by Badr-MOUFAD** [comment]
@GordonYeh39, Thanks for the snippet that reproduces the error.

There was a small bug that occurs when not handling accordingly low surface skill.
The bug is now fixed:

![bug-fixed](https://user-images.githubusercontent.com/65614794/165156432-8df33206-9154-4911-a989-1f1135aa3659.png)


**P.S**: The fix will be taken into account in the next release.
